package com.head_first.aashi.heartsounds_20.enums;

/**
 * Created by Aashish Indorewala on 05-Nov-16.
 */

public enum FinalDiagnosis {
    NO_MURMUR,PHYSIOLOGICAL_MURMUR, AORTIC_STENOSIS,
    AORTIC_REGURGITATION, AORTIC_STENOSIS_WITH_EJECTION_CLICK,
    MITRAL_REGURGITATION, MITRAL_STENOSIS,
    MITRAL_REGURGITATION_DUE_TO_MITRAL_VALVE_PROLAPSE_WITH_MID_SYSTOLIC_CLICK,
    TRICUSPID_REGURGITATION, PULMONARY_STENOSIS,
    PULMONARY_REGURGITATION, PATENT_DUCTUS_ARTERIOSUS,
    FISTULA, VENTRICULAR_SEPTAL_DEFECT, ATRIAL_SEPTAL_DEFECT,
    HYPERTROPHIC_CARDIOMYOPATHY_WITH_LEFT_VENTRICULAR_OUTFLOW_OBSTRUCTION
}
